import {nameCompare} from './functions'
export default [
  {
    name: 'Luebeck',
    reserve_multiplier: 1,
    rich_people: 1800,
    wealthy_people: 2900,
    poor_people: 6500,
    produces: [
      'bricks',
      'fish',
      'grain',
      'hemp',
      'iron goods',
      'pitch',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 31,
      'cattle farm': 0,
      'fisher': 9,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 8,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 36
    }
  },
  {
    name: 'Oslo',
    reserve_multiplier: 2,
    rich_people: 1000,
    wealthy_people: 2200,
    poor_people: 3900,
    produces: [

      'bricks',

      'fish',

      'pig iron',
      'pitch',
      'pottery',
      'skins',
      'timber',
      'whale oil',

    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 12,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 13,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 16,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 7,
      'work shop': 0
    }
  },
  {
    name: 'Stettin',
    reserve_multiplier: 1,
    rich_people: 1400,
    wealthy_people: 2900,
    poor_people: 11100,
    produces: [
      'beer',
      'fish',
      'grain',
      'hemp',
      'salt',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 31,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 7,
      'grain farm': 20,
      'hemp farm': 18,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 26,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Visby',
    reserve_multiplier: 2,
    rich_people: 800,
    wealthy_people: 1400,
    poor_people: 3800,
    produces: [
      'bricks',
      'cloth',
      'grain',
      'hemp',
      'honey',
      'pottery',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 16,
      'vineyard': 0,
      'weaving mill': 11,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Rostock',
    reserve_multiplier: 1,
    rich_people: 900,
    wealthy_people: 1500,
    poor_people: 6000,
    produces: [
      'bricks',
      'grain',
      'hemp',
      'honey',
      'leather',
      'meat',
      'pottery',
      'salt',
    ],
    businesses: {
      'apiary': 16,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 10,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 15,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Aalborg',
    reserve_multiplier: 1,
    rich_people: 1200,
    wealthy_people: 1900,
    poor_people: 6700,
    produces: [
      'bricks',
      'fish',
      'hemp',
      'leather',
      'meat',
      'pig iron',
      'timber',
      'whale oil',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 33,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 16,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 17,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 5,
      'work shop': 0
    }
  },
  {
    name: 'Danzig',
    reserve_multiplier: 1,
    rich_people: 900,
    wealthy_people: 1600,
    poor_people: 4400,
    produces: [
      'beer',
      'grain',
      'hemp',
      'leather',
      'meat',
      'pitch',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 24,
      'fisher': 0,
      'grain farm': 10,
      'hemp farm': 6,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 2,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Malmoe',
    reserve_multiplier: 1,
    rich_people: 700,
    wealthy_people: 1500,
    poor_people: 2800,
    produces: [
      'bricks',
      'cloth',
      'honey',
      'leather',
      'meat',
      'pig iron',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 9,
      'vineyard': 0,
      'weaving mill': 10,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Reval',
    reserve_multiplier: 1.5,
    rich_people: 400,
    wealthy_people: 800,
    poor_people: 2500,
    produces: [
      'grain',
      'iron goods',
      'leather',
      'meat',
      'salt',
      'skins',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 2,
      'hemp farm': 0,
      'hunter': 26,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Riga',
    reserve_multiplier: 1.5,
    rich_people: 400,
    wealthy_people: 700,
    poor_people: 2200,
    produces: [
      'fish',
      'honey',
      'pitch',
      'salt',
      'skins',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 12,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Torun',
    reserve_multiplier: 1,
    rich_people: 400,
    wealthy_people: 900,
    poor_people: 1500,
    produces: [
      'honey',
      'leather',
      'meat',
      'pottery',
      'salt',
      'skins',
      'spices',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Ladoga',
    reserve_multiplier: 2.5,
    rich_people: 500,
    wealthy_people: 1100,
    poor_people: 3000,
    produces: [
      'fish',
      'grain',
      'hemp',
      'honey',
      'pig iron',
      'skins',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 8,
      'grain farm': 0,
      'hemp farm': 2,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Novgorod',
    reserve_multiplier: 2,
    rich_people: 292,
    wealthy_people: 436,
    poor_people: 1356,
    produces: [
      'beer',
      'bricks',
      'honey',
      'leather',
      'meat',
      'pig iron',
      'pitch',
      'skins',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Stockholm',
    reserve_multiplier: 2,
    rich_people: 600,
    wealthy_people: 1200,
    poor_people: 2200,
    produces: [
      'fish',
      'iron goods',
      'leather',
      'meat',
      'pig iron',
      'pottery',
      'timber',
      'whale oil',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 2,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 4,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 5
    }
  },
  {
    name: 'Newcasle',
    reserve_multiplier: 3,
    rich_people: 200,
    wealthy_people: 300,
    poor_people: 1400,
    produces: [
      'fish',
      'grain',
      'wine'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 3,
      'grain farm': 9,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 9,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },

].sort(nameCompare)
