import nameCompare from './functions'
export default [
  {
    name: 'Luebeck',
    rich_people: 546,
    wealthy_people: 1091,
    poor_people: 2387,
    produces: [
      'bricks',
      'fish',
      'grain',
      'hemp',
      'iron goods',
      'pitch',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 4,
      'cattle farm': 0,
      'fisher': 4,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 12
    }
  },
  {
    name: 'Oslo',
    rich_people: 482,
    wealthy_people: 946,
    poor_people: 2688,
    produces: [

      'bricks',

      'fish',

      'pig iron',
      'pitch',
      'pottery',
      'skins',
      'timber',
      'whale oil',

    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 12,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 7,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 5,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Stettin',
    rich_people: 489,
    wealthy_people: 1208,
    poor_people: 3491,
    produces: [
      'beer',
      'fish',
      'grain',
      'hemp',
      'salt',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 13,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 2,
      'grain farm': 6,
      'hemp farm': 2,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 4,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Visby',
    rich_people: 319,
    wealthy_people: 815,
    poor_people: 2239,
    produces: [
      'bricks',
      'cloth',
      'grain',
      'hemp',
      'honey',
      'pottery',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 5,
      'vineyard': 0,
      'weaving mill': 8,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Rostock',
    rich_people: 406,
    wealthy_people: 823,
    poor_people: 2211,
    produces: [
      'bricks',
      'grain',
      'hemp',
      'honey',
      'leather',
      'meat',
      'pottery',
      'salt',
    ],
    businesses: {
      'apiary': 3,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 1,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 4,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Aalborg',
    rich_people: 377,
    wealthy_people: 884,
    poor_people: 2159,
    produces: [
      'bricks',
      'fish',
      'hemp',
      'leather',
      'meat',
      'pig iron',
      'whale oil',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 6,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 3,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 4,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Danzig',
    rich_people: 384,
    wealthy_people: 696,
    poor_people: 2143,
    produces: [
      'beer',
      'grain',
      'hemp',
      'leather',
      'meat',
      'pitch',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 3,
      'fisher': 0,
      'grain farm': 4,
      'hemp farm': 4,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 4,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Malmoe',
    rich_people: 253,
    wealthy_people: 588,
    poor_people: 1139,
    produces: [
      'bricks',
      'cloth',
      'honey',
      'leather',
      'meat',
      'pig iron',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 1,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Reval',
    rich_people: 298,
    wealthy_people: 474,
    poor_people: 2316,
    produces: [
      'grain',
      'iron goods',
      'leather',
      'meat',
      'salt',
      'skins',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 6,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Riga',
    rich_people: 259,
    wealthy_people: 432,
    poor_people: 1473,
    produces: [
      'fish',
      'honey',
      'pitch',
      'salt',
      'skins',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Torun',
    rich_people: 336,
    wealthy_people: 614,
    poor_people: 1554,
    produces: [
      'honey',
      'leather',
      'meat',
      'pottery',
      'salt',
      'skins',
      'spices',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Ladoga',
    rich_people: 268,
    wealthy_people: 644,
    poor_people: 2040,
    produces: [
      'fish',
      'grain',
      'hemp',
      'honey',
      'pig iron',
      'skins',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Novgorod',
    rich_people: 292,
    wealthy_people: 436,
    poor_people: 1356,
    produces: [
      'beer',
      'bricks',
      'honey',
      'leather',
      'meat',
      'pig iron',
      'pitch',
      'skins',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },

].sort(nameCompare)
