import {nameCompare} from './functions'
export default [
  {
    name: 'Luebeck',
    reserve_multiplier: 1,
    rich_people: 921,
    wealthy_people: 1790,
    poor_people: 4173,
    produces: [
      'bricks',
      'fish',
      'grain',
      'hemp',
      'iron goods',
      'pitch',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 17,
      'cattle farm': 0,
      'fisher': 9,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 22
    }
  },
  {
    name: 'Oslo',
    reserve_multiplier: 2,
    rich_people: 281,
    wealthy_people: 617,
    poor_people: 2490,
    produces: [

      'bricks',

      'fish',

      'pig iron',
      'pitch',
      'pottery',
      'skins',
      'timber',
      'whale oil',

    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 12,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 13,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 5,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 3,
      'work shop': 0
    }
  },
  {
    name: 'Stettin',
    reserve_multiplier: 1,
    rich_people: 489,
    wealthy_people: 1521,
    poor_people: 5351,
    produces: [
      'beer',
      'fish',
      'grain',
      'hemp',
      'salt',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 19,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 3,
      'grain farm': 20,
      'hemp farm': 4,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 14,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Visby',
    reserve_multiplier: 2,
    rich_people: 465,
    wealthy_people: 883,
    poor_people: 2520,
    produces: [
      'bricks',
      'cloth',
      'grain',
      'hemp',
      'honey',
      'pottery',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 5,
      'vineyard': 0,
      'weaving mill': 8,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Rostock',
    reserve_multiplier: 1,
    rich_people: 433,
    wealthy_people: 749,
    poor_people: 2889,
    produces: [
      'bricks',
      'grain',
      'hemp',
      'honey',
      'leather',
      'meat',
      'pottery',
      'salt',
    ],
    businesses: {
      'apiary': 6,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 10,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 4,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Aalborg',
    reserve_multiplier: 1,
    rich_people: 494,
    wealthy_people: 1025,
    poor_people: 2461,
    produces: [
      'bricks',
      'fish',
      'hemp',
      'leather',
      'meat',
      'pig iron',
      'timber',
      'whale oil',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 11,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 7,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 12,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Danzig',
    reserve_multiplier: 1,
    rich_people: 331,
    wealthy_people: 696,
    poor_people: 2947,
    produces: [
      'beer',
      'grain',
      'hemp',
      'leather',
      'meat',
      'pitch',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 8,
      'fisher': 0,
      'grain farm': 10,
      'hemp farm': 8,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 4,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Malmoe',
    reserve_multiplier: 1,
    rich_people: 411,
    wealthy_people: 918,
    poor_people: 2084,
    produces: [
      'bricks',
      'cloth',
      'honey',
      'leather',
      'meat',
      'pig iron',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 5,
      'vineyard': 0,
      'weaving mill': 4,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Reval',
    reserve_multiplier: 1.5,
    rich_people: 293,
    wealthy_people: 504,
    poor_people: 2219,
    produces: [
      'grain',
      'iron goods',
      'leather',
      'meat',
      'salt',
      'skins',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 2,
      'hemp farm': 0,
      'hunter': 12,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Riga',
    reserve_multiplier: 1.5,
    rich_people: 200,
    wealthy_people: 436,
    poor_people: 1560,
    produces: [
      'fish',
      'honey',
      'pitch',
      'salt',
      'skins',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Torun',
    reserve_multiplier: 1,
    rich_people: 327,
    wealthy_people: 659,
    poor_people: 1518,
    produces: [
      'honey',
      'leather',
      'meat',
      'pottery',
      'salt',
      'skins',
      'spices',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Ladoga',
    reserve_multiplier: 2.5,
    rich_people: 282,
    wealthy_people: 760,
    poor_people: 2007,
    produces: [
      'fish',
      'grain',
      'hemp',
      'honey',
      'pig iron',
      'skins',
      'timber',
      'wool'
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 8,
      'grain farm': 0,
      'hemp farm': 2,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Novgorod',
    reserve_multiplier: 2,
    rich_people: 292,
    wealthy_people: 436,
    poor_people: 1356,
    produces: [
      'beer',
      'bricks',
      'honey',
      'leather',
      'meat',
      'pig iron',
      'pitch',
      'skins',
      'timber',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 0,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 0,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 0
    }
  },
  {
    name: 'Stockholm',
    reserve_multiplier: 2,
    rich_people: 277,
    wealthy_people: 573,
    poor_people: 1806,
    produces: [
      'fish',
      'iron goods',
      'leather',
      'meat',
      'pig iron',
      'pottery',
      'timber',
      'whale oil',
    ],
    businesses: {
      'apiary': 0,
      'brewery': 0,
      'brick works': 0,
      'cattle farm': 0,
      'fisher': 0,
      'grain farm': 0,
      'hemp farm': 0,
      'hunter': 0,
      'iron smelter': 2,
      'pitch maker': 0,
      'pottery': 0,
      'salt works': 0,
      'sawmill': 4,
      'sheep farm': 0,
      'vineyard': 0,
      'weaving mill': 0,
      'whaler': 0,
      'work shop': 5
    }
  },

].sort(nameCompare)
